#!/bin/bash
#
#	/etc/rc.d/init.d/nodeweblog
#
#	nodeweblog startup script.
#

# Source function library.
. /etc/init.d/functions

TARGET_SCRIPT=/var/nodeweblog/app.js
LOGFILE=/var/log/nodeweblog.log
STDOUTFILE=/var/log/nodeweblog.out
ERRORFILE=/var/log/nodeweblog.err
PIDFILE=/var/run/nodeweblog.pid
FOREVER_DIR=/var/run/forever
LOCKFILE=/var/lock/subsys/nodeweblog

start() {
	echo "Starting nodeweblog: "
	if [ -e $LOCKFILE ]; then
		echo "nodeweblog already running."
	else
		forever start -a -p $FOREVER_DIR --pidfile $PIDFILE -l $LOGFILE -o $STDOUTFILE -e $ERRORFILE $TARGET_SCRIPT
		touch $LOCKFILE
	fi
 	return 0
}	

stop() {
	echo "Shutting down nodeweblog: "
	forever stop $TARGET_SCRIPT
	rm -f $LOCKFILE
	return 0
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	forever list
	;;
    restart)
    	stop
	start
	;;
    *)
	echo "Usage: nodeweblog {start|stop|status|restart}"
	exit 1
	;;
esac
exit $?

